### ISSUE TITLE
Python Bindings: set_sample_rate not working as expected.

### ISSUE THREAD

**Issue by 502E532E** [Tinkerforge/industrial-dual-analog-in-v2-bricklet#1]
When using `set_sample_rate` from python, it seems to have no effect and does not comply its documentation.

First example:
```python
idai.set_sample_rate(255)
print(f"Sample rate is {idai.get_sample_rate()}")
```
results in 
```
Sample rate is 7
```

Second example:
```python
idai.set_sample_rate(256) # Can go up to 976 according to documentation
```
results in the following error
```
Traceback (most recent call last):
  File "\PATH\TO\FILE\test.py", line 19, in <module>
    idai.set_sample_rate(256) # Can go up to 976 according to documentation
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_[...]\LocalCache\local-packages\Python39\site-packages\tinkerforge\bricklet_industrial_dual_analog_in_v2.py", line 220, in set_sample_rate
    self.ipcon.send_request(self, BrickletIndustrialDualAnalogInV2.FUNCTION_SET_SAMPLE_RATE, (rate,), 'B', 0, '')
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_[...]\LocalCache\local-packages\Python39\site-packages\tinkerforge\ip_connection.py", line 1292, in send_request
    payload = pack_payload(data, form)
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_[...]\LocalCache\local-packages\Python39\site-packages\tinkerforge\ip_connection.py", line 259, in pack_payload
    packed += struct.pack('<' + f, d)
struct.error: ubyte format requires 0 <= number <= 255
```

Full testing code:
```python
from tinkerforge.ip_connection import IPConnection
from tinkerforge.bricklet_industrial_dual_analog_in_v2 import (
    BrickletIndustrialDualAnalogInV2,
)

HOST = "localhost"
PORT = 4223
UID = "INSERT UID HERE"

if __name__ == "__main__":
    ipcon = IPConnection()
    idai = BrickletIndustrialDualAnalogInV2(UID, ipcon)

    ipcon.connect(HOST, PORT)

    idai.set_sample_rate(255)
    print(f"Sample rate is {idai.get_sample_rate()}")

    idai.set_sample_rate(256) # Can go up to 976 according to documentation

    ipcon.disconnect()
```

It is also possible that I misunderstood what the method is supposed to to. Any help is appreciated!

**Comment by borg42** [comment]
You need to use the constants:
SAMPLE_RATE_976_SPS
SAMPLE_RATE_488_SPS
SAMPLE_RATE_244_SPS
SAMPLE_RATE_122_SPS
SAMPLE_RATE_61_SPS
SAMPLE_RATE_4_SPS
SAMPLE_RATE_2_SPS
SAMPLE_RATE_1_SPS

For example:
`idai.set_sample_rate(idai.SAMPLE_RATE_976_SPS)`

**Comment by 502E532E** [comment]
Alright, that works well. Thank you very much!
